---
    -   name: Installing mysql on Debian
        apt:
            name: {{ item }}
            state: present
        with_items:
        -   mysql-server
        -   mysql-client
        -   mysql-common
        -   python-mysqldb
        -   python
        -   python3
        when:
            ansible_os_family == "Debian"
    
    -   name: Copy the file my.cnf
        template:
            src: my.cnf.j2
            dest:
            owner: root
            mode: 0600

            
    